setup:
	git clone https://github.com/AkashGanesan/video-context-transcription
	cd video-context-transcription
	virtualenv -p python3 env
	source env/bin/activate
	pip install --upgrade pip
	pip install -r requirements

	# For spacy and nltk modules
	python -m spacy download en_core_web_lg
	python -m nltk.downloader all

demo:

